version: '3.3'
services:
        registry:
                image: registry:2
                ports:
                        - 5000:5000
                volumes:
                        - /g/registryspace:/var/lib/registry
                networks:
                        - showcase
networks:
        showcase:
                external: true
